// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMJyaWIHqpHL51P3x0KneC_S8zwqFVDrk',
    appId: '1:859242624094:web:9e7c24d96cfc28495170cf',
    messagingSenderId: '859242624094',
    projectId: 'portfolio-570d2',
    authDomain: 'portfolio-570d2.firebaseapp.com',
    storageBucket: 'portfolio-570d2.firebasestorage.app',
    measurementId: 'G-7KSP21D8FZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrLtrW4Phd0zZ8TXyUro0mECCaFYCE7Us',
    appId: '1:859242624094:android:536b7224f4ea450c5170cf',
    messagingSenderId: '859242624094',
    projectId: 'portfolio-570d2',
    storageBucket: 'portfolio-570d2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0oJrntj5pYrmj93arQ5mCIGZO6LeIdkU',
    appId: '1:859242624094:ios:5819f8098aacc8f15170cf',
    messagingSenderId: '859242624094',
    projectId: 'portfolio-570d2',
    storageBucket: 'portfolio-570d2.firebasestorage.app',
    iosBundleId: 'com.example.proftolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0oJrntj5pYrmj93arQ5mCIGZO6LeIdkU',
    appId: '1:859242624094:ios:5819f8098aacc8f15170cf',
    messagingSenderId: '859242624094',
    projectId: 'portfolio-570d2',
    storageBucket: 'portfolio-570d2.firebasestorage.app',
    iosBundleId: 'com.example.proftolio',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMJyaWIHqpHL51P3x0KneC_S8zwqFVDrk',
    appId: '1:859242624094:web:b0ff2e4c364098785170cf',
    messagingSenderId: '859242624094',
    projectId: 'portfolio-570d2',
    authDomain: 'portfolio-570d2.firebaseapp.com',
    storageBucket: 'portfolio-570d2.firebasestorage.app',
    measurementId: 'G-00LKFXWH7Z',
  );
}
